export const DefaultFirstGrid = [
  {
    id: 1,
    type: "Regular",
    inEdit: true,
    amountEdit: false,
    hours: 0,
    amount: 0,
    fieldAmount: "prRegAmount",
    fieldHour: "prRegHours",
    apiParaMeterName: "RegularHours",
  },
  {
    id: 2,
    type: "Overtime",
    inEdit: true,
    amountEdit: false,
    hours: 0,
    amount: 0,
    fieldAmount: "prOTAmount",
    fieldHour: "prOtHours",
    apiParaMeterName: "OverTimeHours",
  },
  {
    id: 3,
    type: "Holiday Work",
    inEdit: true,
    amountEdit: false,
    hours: 0,
    amount: 0,
    fieldAmount: "prHolidayAmount",
    fieldHour: "prHolidayHours",
    apiParaMeterName: "HolidayWorkHours",
  },
  {
    id: 4,
    type: "Holiday Overtime",
    inEdit: true,
    amountEdit: false,
    hours: 0,
    amount: 0,
    fieldAmount: "holidayotamount",
    fieldHour: "holidayOT",
    apiParaMeterName: "HolidayOTHours",
  },
  {
    id: 5,
    type: "ST Hours",
    inEdit: true,
    amountEdit: false,
    hours: 0,
    amount: 0,
    fieldAmount: "prSTHoursAmount",
    fieldHour: "prSTHours",
    apiParaMeterName: "STHours",
  },
  {
    id: 6,
    type: "Non ST Hours",
    inEdit: true,
    amountEdit: false,
    hours: 0,
    amount: 0,
    fieldAmount: "prNonSTHoursAmount",
    fieldHour: "prNonSTHours",
    apiParaMeterName: "NonSTHours",
  },
  {
    id: 7,
    type: "Adjustment",
    inEdit: true,
    amountEdit: true,
    hours: 0,
    amount: 0,
    fieldAmount: "pradjustment",
    fieldHour: "adjustmentHours",
    apiParaMeterName: "AdjustmentHours",
    allowNagative: true
  },
  {
    id: 8,
    type: "Total",
    inEdit: true,
    amountEdit: false,
    hours: 0,
    amount: 0,
    fieldAmount: "prGross",
    fieldHour: "prTotalHours",
    apiParaMeterName: "LeaveWithoutPay",
  },
];
export const DefaultSecondGrid = [
  {
    id: 3,
    type: "Vacation Earned",
    inEdit: false,
    hours: "",
    fieldHour: "prVacaEarned",
    allowNagative: true
  },
  {
    id: 4,
    type: "Vacation Adjustment",
    inEdit: true,
    hours: "",
    fieldHour: "vacaAdd",
    allowNagative: true
  },
  {
    id: 5,
    type: "Sick Earned",
    inEdit: false,
    hours: "",
    fieldHour: "prSickTimeEarned",
  },
  {
    id: 6,
    type: "Sick Adjustment",
    inEdit: true,
    hours: "",
    fieldHour: "sickAdd",
    allowNagative: true
  }
];
export const DefaultThirdGrid = [
  {
    id: 1,
    type: "Vacation Used",
    inEdit: false,
    hours: 0,
    fieldHour: "prVacaUsed",
  },
  {
    id: 2,
    type: "Sick Used",
    inEdit: false,
    hours: 0,
    fieldHour: "prSickUsed",
  },
  {
    id: 5,
    type: "Personal",
    inEdit: false,
    hours: 0,
    fieldHour: "prPersonalUsed",
  },
  {
    id: 6,
    type: "Pro Day Used",
    inEdit: false,
    hours: 0,
    fieldHour: "prProdayUsed",
  },
  {
    id: 7,
    type: "Calamity",
    inEdit: false,
    hours: 0,
    fieldHour: "calimity",
  },
  {
    id: 8,
    type: "Comp Time Used",
    inEdit: false,
    hours: 0,
    fieldHour: "prOther",
  },
  {
    id: 9,
    type: "Paid Hol",
    inEdit: false,
    hours: 0,
    fieldHour: "holidayPaid",
  },
  {
    id: 10,
    type: "Break",
    inEdit: false,
    hours: 0,
    fieldHour: "breakTime",
  },
  {
    id: 11,
    type: "Other Used",
    inEdit: false,
    hours: 0,
    fieldHour: "otherUsed",
  },
  {
    id: 12,
    type: "Taxable Fringe",
    inEdit: false,
    hours: 0,
    fieldHour: "taxableFringe",
  },
  {
    id: 13,
    type: "Fed Paid Sick",
    inEdit: false,
    hours: 0,
    fieldHour: "fedPaidSickUsed",
  },
  {
    id: 14,
    type: "Emerg FMLA",
    inEdit: false,
    hours: 0,
    fieldHour: "emergencyFmlaUsed",
  },
  {
    id: 15,
    type: "LWOP",
    inEdit: true,
    hours: "",
    fieldHour: "prUnexcused",
  },
];
