export const tmpFunctionData = [
  {
    functionS_ID: 1,
    functionS_KEY: "ManageFund",
    functionS_NAME: "Manage Fund",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 101,
  },
  {
    functionS_ID: 2,
    functionS_KEY: "TransferFund",
    functionS_NAME: "Transfer Fund",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 101,
  },
  {
    functionS_ID: 3,
    functionS_KEY: "CalculateBalance",
    functionS_NAME: "Calculate Balance",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 101,
  },
  {
    functionS_ID: 4,
    functionS_KEY: "ManageAmount",
    functionS_NAME: "Manage Amount",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 101,
  },
  {
    functionS_ID: 6,
    functionS_KEY: "InactivateFund",
    functionS_NAME: "Inactive Fund",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 101,
  },
  {
    functionS_ID: 7,
    functionS_KEY: "FSMI",
    functionS_NAME: "Show Modified Info",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 101,
  },
  {
    functionS_ID: 10,
    functionS_KEY: "ManageCACE",
    functionS_NAME: "Manage CAC Expense ",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 102,
  },
  {
    functionS_ID: 11,
    functionS_KEY: "TransferCACEAmount",
    functionS_NAME: "Transfer Amount",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 102,
  },
  {
    functionS_ID: 12,
    functionS_KEY: "CalculateCACECarryover",
    functionS_NAME: "Calculate Expense Carryover",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 102,
  },
  {
    functionS_ID: 13,
    functionS_KEY: "ManageCACEAmount",
    functionS_NAME: "Manage Amount",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 102,
  },
  {
    functionS_ID: 14,
    functionS_KEY: "InactivateCACE",
    functionS_NAME: "Inactive Fund",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 102,
  },
  {
    functionS_ID: 15,
    functionS_KEY: "CACESMI",
    functionS_NAME: "Show Modified Info",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 102,
  },
  {
    functionS_ID: 19,
    functionS_KEY: "ManageCACR",
    functionS_NAME: "Manage CAC Revenue ",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 103,
  },
  {
    functionS_ID: 20,
    functionS_KEY: "ManageCACRAmount",
    functionS_NAME: "Manage Amount",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 103,
  },
  {
    functionS_ID: 21,
    functionS_KEY: "InactivateCACR",
    functionS_NAME: "Inactive Fund",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 103,
  },
  {
    functionS_ID: 22,
    functionS_KEY: "CACRSMI",
    functionS_NAME: "Show Modified Info",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 103,
  },
  {
    functionS_ID: 23,
    functionS_KEY: "ManageProgram",
    functionS_NAME: "Manage Program ",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 104,
  },
  {
    functionS_ID: 24,
    functionS_KEY: "InactivateProgram",
    functionS_NAME: "Inactive Program",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 104,
  },
  {
    functionS_ID: 25,
    functionS_KEY: "ProgramSMI",
    functionS_NAME: "Show Modified Info",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 104,
  },
  {
    functionS_ID: 26,
    functionS_KEY: "ManageDepartment",
    functionS_NAME: "Manage Department ",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 105,
  },
  {
    functionS_ID: 27,
    functionS_KEY: "InactivateDepartment",
    functionS_NAME: "Inactive Department",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 105,
  },
  {
    functionS_ID: 28,
    functionS_KEY: "DepartmentSMI",
    functionS_NAME: "Show Modified Info",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 105,
  },
  {
    functionS_ID: 29,
    functionS_KEY: "ManageAccount",
    functionS_NAME: "Manage Account ",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 106,
  },
  {
    functionS_ID: 30,
    functionS_KEY: "InactivateAccount",
    functionS_NAME: "Inactive Account",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 106,
  },
  {
    functionS_ID: 31,
    functionS_KEY: "AccountSMI",
    functionS_NAME: "Show Modified Info",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 106,
  },
  {
    functionS_ID: 32,
    functionS_KEY: "ManageSubAccount",
    functionS_NAME: "Manage Sub Account ",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 107,
  },
  {
    functionS_ID: 33,
    functionS_KEY: "InactivateSubAccount",
    functionS_NAME: "Inactive Sub Account",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 107,
  },
  {
    functionS_ID: 34,
    functionS_KEY: "SubAccountSMI",
    functionS_NAME: "Show Modified Info",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 107,
  },
  {
    functionS_ID: 35,
    functionS_KEY: "ManageIHACE",
    functionS_NAME: "Manage IHAC Expense ",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 108,
  },
  {
    functionS_ID: 36,
    functionS_KEY: "TransferIHACEAmount",
    functionS_NAME: "Transfer Amount",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 108,
  },
  {
    functionS_ID: 37,
    functionS_KEY: "CalculateIHACECarryover",
    functionS_NAME: "Calculate Expense Carryover",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 108,
  },
  {
    functionS_ID: 38,
    functionS_KEY: "ManageIHACEAmount",
    functionS_NAME: "Manage Amount",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 108,
  },
  {
    functionS_ID: 39,
    functionS_KEY: "InactivateIHACE",
    functionS_NAME: "Inactive IHAC",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 108,
  },
  {
    functionS_ID: 40,
    functionS_KEY: "IHACESMI",
    functionS_NAME: "Show Modified Info",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 108,
  },
  {
    functionS_ID: 41,
    functionS_KEY: "ManageIHACR",
    functionS_NAME: "Manage IHAC Revenue ",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 109,
  },
  {
    functionS_ID: 42,
    functionS_KEY: "ManageIHACRAmount",
    functionS_NAME: "Manage Amount",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 109,
  },
  {
    functionS_ID: 43,
    functionS_KEY: "InactivateIHACR",
    functionS_NAME: "Inactive IHAC",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 109,
  },
  {
    functionS_ID: 44,
    functionS_KEY: "IHACRSMI",
    functionS_NAME: "Show Modified Info",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 109,
  },
  {
    functionS_ID: 45,
    functionS_KEY: "ManageAccountReceivable ",
    functionS_NAME: "Manage Account Receivable ",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 110,
  },
  {
    functionS_ID: 47,
    functionS_KEY: "AccountReceivableSMI",
    functionS_NAME: "Show Modified Info",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 110,
  },
  {
    functionS_ID: 48,
    functionS_KEY: "ManageAccountReceivableRevenue",
    functionS_NAME: "Manage Account Receivable Revenue ",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 111,
  },
  {
    functionS_ID: 50,
    functionS_KEY: "AccountReceivableRevenueSMI",
    functionS_NAME: "Show Modified Info",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 111,
  },
  {
    functionS_ID: 60,
    functionS_KEY: "PreviousYearRevenue",
    functionS_NAME: "Previous Year Revenue",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 112,
  },
  {
    functionS_ID: 61,
    functionS_KEY: "ManagePurchaseOrder",
    functionS_NAME: "Manage Purchase Order",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 113,
  },
  {
    functionS_ID: 62,
    functionS_KEY: "ManageIHPO",
    functionS_NAME: "Manage IHPO",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 113,
  },
  {
    functionS_ID: 63,
    functionS_KEY: "ManageVoucher",
    functionS_NAME: "Manage Voucher",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 113,
  },
  {
    functionS_ID: 64,
    functionS_KEY: "RequestIHPO",
    functionS_NAME: "Request IHPO",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 114,
  },
  {
    functionS_ID: 65,
    functionS_KEY: "CreateVendor",
    functionS_NAME: "Create Vendor",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 114,
  },
  {
    functionS_ID: 66,
    functionS_KEY: "ApproveIHPO",
    functionS_NAME: "Approve IHPO",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 115,
  },
  {
    functionS_ID: 67,
    functionS_KEY: "PreviousYearExpense",
    functionS_NAME: "PreviousYearExpense",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 116,
  },
  {
    functionS_ID: 68,
    functionS_KEY: "AddSAC",
    functionS_NAME: "Add SAC",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 115,
  },
  {
    functionS_ID: 69,
    functionS_KEY: "AddPO",
    functionS_NAME: "Add PO Details",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 115,
  },
  {
    functionS_ID: 70,
    functionS_KEY: "AddIHAC",
    functionS_NAME: "Add IHAC Details",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 115,
  },
  {
    functionS_ID: 5011,
    functionS_KEY: "ManageInventory\r\n",
    functionS_NAME: "ManageInventory\r\n",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 501,
  },
  {
    functionS_ID: 5012,
    functionS_KEY: "InventorySMI\r\n",
    functionS_NAME: "InventorySMI\r\n",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 501,
  },
  {
    functionS_ID: 5021,
    functionS_KEY: "ManageAssets\r\n",
    functionS_NAME: "ManageAssets\r\n",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 502,
  },
  {
    functionS_ID: 5022,
    functionS_KEY: "AssetsSMI\r\n",
    functionS_NAME: "AssetsSMI\r\n",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 502,
  },
  {
    functionS_ID: 10011,
    functionS_KEY: "ManageOrganization",
    functionS_NAME: "Manage Organization",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 1001,
  },
  {
    functionS_ID: 10012,
    functionS_KEY: "ActivateOrganization",
    functionS_NAME: "Activate Organization",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 1001,
  },
  {
    functionS_ID: 10013,
    functionS_KEY: "RegistrationLink",
    functionS_NAME: "Registration Link",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 1001,
  },
  {
    functionS_ID: 10014,
    functionS_KEY: "OrgnizationSMI",
    functionS_NAME: "Orgnization SMI",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 1001,
  },
  {
    functionS_ID: 20101,
    functionS_KEY: "ManageProjectCosting",
    functionS_NAME: "Manage Project Costing",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 201,
  },
  {
    functionS_ID: 20102,
    functionS_KEY: "ManageMaterialSupplies",
    functionS_NAME: "Manage Material Supplies",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 201,
  },
  {
    functionS_ID: 20103,
    functionS_KEY: "MaterialSuppliesSMI",
    functionS_NAME: "Material Supplies SMI",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 201,
  },
  {
    functionS_ID: 20104,
    functionS_KEY: "ManageMaterialSupplies",
    functionS_NAME: "Manage Material Supplies",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 201,
  },
  {
    functionS_ID: 20105,
    functionS_KEY: "ManageLabour",
    functionS_NAME: "Manage Labour",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 201,
  },
  {
    functionS_ID: 20106,
    functionS_KEY: "ManageLabourSMI",
    functionS_NAME: "Manage Labour SMI",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 201,
  },
  {
    functionS_ID: 20107,
    functionS_KEY: "ManageEquipment",
    functionS_NAME: "Manage Equipment",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 201,
  },
  {
    functionS_ID: 20108,
    functionS_KEY: "ManageEquipmentSMI",
    functionS_NAME: "Manage Equipment SMI",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 201,
  },
  {
    functionS_ID: 20109,
    functionS_KEY: "ManageRevenue",
    functionS_NAME: "Manage Revenue",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 201,
  },
  {
    functionS_ID: 20110,
    functionS_KEY: "ManageRevenueSMI",
    functionS_NAME: "Manage Revenue SMI",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 201,
  },
  {
    functionS_ID: 20111,
    functionS_KEY: "ManagePCReports",
    functionS_NAME: "Manage PCosting Reports",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 201,
  },
  {
    functionS_ID: 20201,
    functionS_KEY: "ManageEquipmentSetup",
    functionS_NAME: "Manage Equipment Setup",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 202,
  },
  {
    functionS_ID: 20202,
    functionS_KEY: "ManageEquipmentSetupSMI",
    functionS_NAME: "Manage Equipment Setup SMI",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 202,
  },
  {
    functionS_ID: 20301,
    functionS_KEY: "ManageWorkSetup",
    functionS_NAME: "ManageWorkSetup",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 203,
  },
  {
    functionS_ID: 20302,
    functionS_KEY: "ManageWorkSetupSMI",
    functionS_NAME: "Manage Work Setup SMI",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 203,
  },
  {
    functionS_ID: 20401,
    functionS_KEY: "ManageLocationSetup",
    functionS_NAME: "Manage Location Setup",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 204,
  },
  {
    functionS_ID: 20402,
    functionS_KEY: "ManageLocationSetupSMI",
    functionS_NAME: "Manage Location Setup SMI",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 204,
  },
  {
    functionS_ID: 30101,
    functionS_KEY: "ManageEmployeeTimecardSetup\r\n",
    functionS_NAME: "Manage  Employee Timecard Setup\r\n",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 301,
  },
  {
    functionS_ID: 30102,
    functionS_KEY: "ManageEmployeeTimecardSetupSMI\r\n",
    functionS_NAME: "Manage  Employee Timecard Setup SMI\r\n",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 301,
  },
  {
    functionS_ID: 30201,
    functionS_KEY: "EmployeeScheduleSetup\r\n",
    functionS_NAME: "Manage Employee Timecard Schedule\r\n",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 302,
  },
  {
    functionS_ID: 30301,
    functionS_KEY: "ManageHolidaySchedule\r\n",
    functionS_NAME: "ManageHolidaySchedule\r\n",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 303,
  },
  {
    functionS_ID: 30302,
    functionS_KEY: "ManageHolidayScheduleSMI\r\n",
    functionS_NAME: "ManageHolidayScheduleSMI\r\n",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 303,
  },
  {
    functionS_ID: 30401,
    functionS_KEY: "ManageSupervisorSetup\r\n",
    functionS_NAME: "ManageSupervisorSetup\r\n",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 304,
  },
  {
    functionS_ID: 30402,
    functionS_KEY: "SupervisorSetupSMI\r\n",
    functionS_NAME: "SupervisorSetup Show Modified Info\r\n",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 304,
  },
  {
    functionS_ID: 30501,
    functionS_KEY: "ManageVSPSetup\r\n",
    functionS_NAME: "ManageVSPSetup\r\n",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 305,
  },
  {
    functionS_ID: 30502,
    functionS_KEY: "ManagerVSPSetupSMI\r\n",
    functionS_NAME: "ManagerVSPSetupSMI\r\n",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 305,
  },
  {
    functionS_ID: 30601,
    functionS_KEY: "ManageTimecard\r\n",
    functionS_NAME: "Manage Timecard\r\n",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 306,
  },
  {
    functionS_ID: 30602,
    functionS_KEY: "TimecardSubmission\r\n",
    functionS_NAME: "Timecard Submission\r\n",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 306,
  },
  {
    functionS_ID: 30603,
    functionS_KEY: "ManageTimecardApproval\r\n",
    functionS_NAME: "Manage Timecard Approval\r\n",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 306,
  },
  {
    functionS_ID: 30604,
    functionS_KEY: "ManualTimeEntry\r\n",
    functionS_NAME: "ManualTimeEntry\r\n",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 306,
  },
  {
    functionS_ID: 30605,
    functionS_KEY: "ClockinClockout\r\n",
    functionS_NAME: "ClockinClockout\r\n",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 306,
  },
  {
    functionS_ID: 30606,
    functionS_KEY: "ShowSupervisorOwntimecard\r\n",
    functionS_NAME: "ShowSupervisorOwntimecard\r\n",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 306,
  },
  {
    functionS_ID: 30701,
    functionS_KEY: "ShowEmployeeForTheDay",
    functionS_NAME: "Show Employee For The Day",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 307,
  },
  {
    functionS_ID: 30801,
    functionS_KEY: "ShowEmployeeFutureLeave",
    functionS_NAME: "Show Employee Future Leave",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 308,
  },
  {
    functionS_ID: 30901,
    functionS_KEY: "ManageEmployeeLeaveRequest",
    functionS_NAME: "Manage Employee Leave Request",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 309,
  },
  {
    functionS_ID: 30902,
    functionS_KEY: "SubmitEmployeeLeaveRequest\r\n",
    functionS_NAME: "Submit Employee Leave Request\r\n",
    applicationS_ID: 1,
    functionS_GROUPS_ID: 309,
  },
];
